name: FFmpeg Loop Smart

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Clone repo
        uses: actions/checkout@v4

      - name: 🟢 Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: 📁 Create streams
        run: mkdir -p streams

      - name: 🚀 Start Streaming
        run: |
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7756.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein1.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7755.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein2.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7749.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein3.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7754.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein4.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7753.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein5.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7752.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein6.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7748.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein7.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7750.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein8.m3u8 &
          ffmpeg -re -i "http://t77ert.top/live/d8:e0:e1:6b:af:93/5Qw87kD9keEO7gd/7747.m3u8" -c copy -f hls -hls_time 4 -hls_list_size 5 streams/bein9.m3u8 &

      # ⏳ انتظر 5h45min
      - name: ⏳ Wait before restart
        run: sleep 20700

      # 🔁 شغل Run جديد قبل ما القديم يموت
      - name: 🔁 Start new workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/stream.yml/dispatches \
          -d '{"ref":"main"}'

      # ⏱ خلي القديم يكمل 10 دقائق
      - name: ⏱ Grace time
        run: sleep 600

      - name: 🛑 Stop
        run: echo "Old workflow stopping..."
